<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TfmGroupDotNet)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition="'$(UsePackageReferences)' != 'true'">
    <ProjectReference Include="..\War3Net.IO.Compression\War3Net.IO.Compression.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(UsePackageReferences)' == 'true'">
    <PackageReference Include="WCSharp.War3Net.IO.Compression" Version="$(War3NetIOCompressionVersion)" />
  </ItemGroup>

</Project>
