name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: windows-latest
    name: Build and publish to NuGet

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '5.x'

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore War3NetPublish.slnf

      - name: Build project
        run: dotnet build War3NetPublish.slnf --configuration Release --no-restore --property WarningLevel=0

      - name: Pack War3Net.Build
        run: dotnet pack War3NetPublish.slnf --configuration Release --no-build -o out /p:UsePackageReferences=true

      - name: Push to NuGet
        run: dotnet run --project ./Tools.NuGetPusher/Tools.NuGetPusher.csproj -- --ApiKey ${{ secrets.NUGET_API_KEY }} --PackageDirectory out
